#!/usr/bin/env bash

set -e

clear

# Change to dir of script
cd "$(dirname "$0")"

# Useful variables
BASEDIR="$(pwd)"
BACKUPDIR="$BASEDIR/.backup"

rm -rf $BACKUPDIR
mkdir -p $BACKUPDIR

# Set up symlinks
for raw_filepath in $(find . -name '*.symlink'); do
    filepath=$(echo $raw_filepath | cut -c 3- | rev | cut -c 9- | rev)
    filename="$HOME/$filepath"
    sourcepath="$BASEDIR/$raw_filepath"

    # create backup if the file already exists
    if [[ -e $filename ]] && ! [[ $(diff --brief $raw_filepath $filename) ]]; then
    mv -v $filename $BACKUPDIR
    fi

    mkdir -p $(dirname $filename)
    ln -Fs $sourcepath $filename
done

mkdir -p $HOME/.config/nvim/autoload
if [ ! -f ~/.config/nvim/autoload/plug.vim ]; then
    curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim +PlugClean +PlugInstall +PlugUpdate +qall

echo "Done!"
echo "Old files has been put in $BACKUPDIR"
