#!/usr/bin/env zsh

set -e

( # Keep all actions within limited scope
# Change to dir of script
cd "$(dirname "$0")"

# Useful variables
BASEDIR="$(pwd)"
BACKUPDIR="$BASEDIR/.backup"

rm -rf $BACKUPDIR
mkdir -p $BACKUPDIR

# install zprezto
type zsh || echo "Install zsh to continue"
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto" || echo "zprezto already installed"

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -fs "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh || echo "zplug already installed"

git clone --depth=1 https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm || echo
git clone --depth=1 https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell || echo


# Set up symlinks
for raw_filepath in $(ls | grep ".symlink"); do
    filepath=".$(echo $raw_filepath | sed 's/.symlink//g')"
    filename="$HOME/$filepath"
    sourcepath="$BASEDIR/$raw_filepath"

    # create backup if the file already exists
    if [[ -e $filename ]] && ! [[ $(diff --brief $raw_filepath $filename) ]]; then
        mv -v $filename $BACKUPDIR
    fi

    mkdir -p $(dirname $filename)
    ln -fs $sourcepath $filename
done

source ~/.zshrc && zplug install

git config --global core.excludesfile "$HOME/.gitignore"
git update-index --assume-unchanged local_overrides.zsh.symlink
git config --global core.editor "vim"

echo "Done!"
echo "Old files has been put in $BACKUPDIR"

echo "Run p10k configure to set up theme"

)
