#!/usr/bin/env bash

set -e

( # Keep all actions within limited scope
# Change to dir of script
cd "$(dirname "$0")"

# Useful variables
BASEDIR="$(pwd)"
BACKUPDIR="$BASEDIR/.backup"

rm -rf $BACKUPDIR
mkdir -p $BACKUPDIR

GIT_PREVIOUS_NAME=$(git config --global user.name || echo "")
GIT_PREVIOUS_EMAIL=$(git config --global user.email || echo "")

# Set up symlinks
for raw_filepath in $(ls | grep ".symlink"); do
    filepath=".$(echo $raw_filepath | sed 's/.symlink//g')"
    filename="$HOME/$filepath"
    sourcepath="$BASEDIR/$raw_filepath"

    # create backup if the file already exists
    if [[ -e $filename ]] && ! [[ $(diff --brief $raw_filepath $filename) ]]; then
        mv -v $filename $BACKUPDIR
    fi

    mkdir -p $(dirname $filename)
    ln -fs $sourcepath $filename
done

# set up path-specific values
[[ -n "$GIT_PREVIOUS_NAME" ]] && git config --global user.name "$GIT_PREVIOUS_NAME"
[[ -n "$GIT_PREVIOUS_EMAIL" ]] && git config --global user.name "$GIT_PREVIOUS_EMAIL"
git config --global core.excludesfile "$HOME/.gitignore"

echo "Done!"
echo "Old files has been put in $BACKUPDIR"

)
